// Run in console of browser on grok page, press ctrl shift and i to open cosnole, will ask for permission to copy paste into console if you have never done it before. must type what it says first, one time only.
// After 2 downloads page will ask for permission to download multiple files.
// After that it just keeps making images. Edit the prompts as you desire.

// List of base prompts
const basePrompts = [
    'pinup girl with red head long hair pig tails, blue cheerleader skirt, red fishnet leggings, purple cut off sport jersey that says NanoCheeZe, sunglasses, nose ring, belly ring',
    'pinup girl with red head long hair pig tails, blue dress, red fishnet leggings, and a banner that says NanoCheeZe, sunglasses, nose ring, belly ring',
    'pinup girl with red head long hair pig tails, shiny blue leather pants, green shoes, purple cut off top that says NanoCheeZe, sunglasses, nose ring, belly ring',
    'pinup girl with red head long hair pig tails, blue cyberpunk suit, red fishnet leggings, purple torso armor that says NanoCheeZe, cyborg visor, nose ring, belly ring',
    'pinup girl with red head long hair pig tails, blue jeans, green shoes, purple t-shirt that says NanoCheeZe, sunglasses, nose ring, belly ring',
    'pinup girl with red head long hair pig tails, in a vintage dress with floral strawberry print, wearing sunglasses and holding a sign that says NanoCheeZe, red lipstick, nose ring, belly ring'
];

// Function to randomly replace 'NanoCheeZe' with 'MEQUAVIS' or 'Hybrid Tales'
function replaceNanoCheeze(prompt) {
    const options = ['NanoCheeZe', 'NanoCheeZe', 'NanoCheeZe', 'NCZ', 'MEQUAVIS', 'Hybrid Tales'];
    const replacement = options[Math.floor(Math.random() * options.length)];
    return prompt.replace('NanoCheeZe', replacement);
}

// Function to randomly select a base prompt (1 out of 5 times)
function getRandomBasePrompt() {
    if (Math.random() <= 0.5) { // 50% chance to change the base prompt
        const randomIndex = Math.floor(Math.random() * basePrompts.length);
        return basePrompts[randomIndex];
    } else {
        return basePrompts[0]; // Default base prompt
    }
}

(function automateInteraction() {
    // Check if error count exists in localStorage, otherwise initialize it to 0
    let errorCount = localStorage.getItem('errorCount') ? parseInt(localStorage.getItem('errorCount')) : 0;
    let lastProcessedImageSrc = null;  // Keep this in the current session

    // Generate the base prompt
    let basePrompt = getRandomBasePrompt();
    basePrompt = replaceNanoCheeze(basePrompt);

    console.log('Generated Prompt:', basePrompt);

    // Lists of extra sentences

const extraList1 = [
    'holding a giant strawberry',
    'holding a giant triangular block of cheese',
    'in a park',
    'with a playful smile',
    'wearing bracelets',
    'surrounded by butterflies',
    'in the sim',
    'on knees',
    'using a smart phone',
    'whole body shot',
    'holding a bouquet of flowers',
    'sitting on a bench',
    'laughing joyfully',
    'wearing a hat',
    'surrounded by cherry blossoms',
    'in a virtual reality setting',
    'kneeling gracefully',
    'using a tablet',
    'full-length portrait',
    'holding a lantern',
    'dancing gracefully',
    'playing a guitar',
    'reading a book',
    'holding a cup of coffee',
    'with sparkling eyes',
    'wearing a crown',
    'holding a sparkler',
    'standing confidently',
    'with flowing hair',
    'holding a parasol',
    'posing with a skateboard',
    'holding a paintbrush',
    'wearing a scarf',
    'with a thoughtful expression',
    'holding a bouquet of balloons',
    'posing with a vintage camera',
    'wearing neon sunglasses',
    'holding a map',
    'with a serene expression',
    'holding a microphone',
    'wearing a bowtie',
    'holding a bouquet of roses',
    'with a mischievous grin',
    'holding a basketball',
    'wearing a denim jacket',
    'holding a violin',
    'with a radiant smile',
    'holding a flashlight',
    'wearing a headband',
    'holding a beach ball',
    'with a relaxed posture',
    'holding a stack of books',
    'wearing a leather jacket',
    'holding a smartphone',
    'with a joyful laugh',
    'holding a bouquet of lilies',
    'wearing a floral dress',
    'holding a tennis racket',
    'with an excited expression',
    'holding a skateboard',
    'wearing a beanie',
    'holding a microphone',
    'with a confident stance',
    'holding a camera',
    'wearing a raincoat',
    'holding a gift box',
    'with a curious look',
    'holding a flower crown',
    'wearing a tutu',
    'holding a magic wand',
    'with a dreamy gaze',
    'holding a teddy bear',
    'wearing a hoodie',
    'holding a paint palette',
    'with a joyful demeanor',
    'holding a smartphone',
    'wearing a tank top',
    'holding a soccer ball',
    'with a bright smile',
    'holding a keychain',
    'wearing a bomber jacket',
    'holding a water bottle',
    'with a friendly grin',
    'holding a skateboard helmet',
    'wearing a floral headband',
    'holding a set of keys',
    'with an adventurous spirit',
    'holding a smartphone',
    'wearing a summer hat',
    'holding a reusable bag',
    'with a content expression',
    'holding a notebook',
    'wearing a rain hat',
    'holding a paint tube',
    'with an enthusiastic smile',
    'holding a coffee cup',
    'wearing a graphic tee',
    'holding a portable speaker',
    'with a relaxed smile',
    'holding a fidget spinner',
    'wearing a sports jersey',
    'holding a yoga mat',
    'with a peaceful aura',
    'holding a journal',
    'wearing a knitted sweater',
    'holding a water gun',
    'with a vibrant energy',
    'holding a hiking stick',
    'wearing a sun visor',
    'holding a frisbee',
    'with a playful demeanor',
    'holding a cocktail glass',
    'wearing a sequined top',
    'holding a bouquet of wildflowers',
    'with a charming smile',
    'holding a crystal ball',
    'wearing a vintage hat',
    'holding a bouquet of daisies',
    'with a lively expression',
    'holding a bouquet of tulips',
    'wearing a pearl necklace',
    'holding a bouquet of sunflowers',
    'with a radiant presence',
    'holding a bouquet of orchids',
    'wearing a feathered headpiece',
    'holding a bouquet of lavender',
    'with a graceful posture',
    'holding a bouquet of peonies',
    'wearing a lace scarf',
    'holding a bouquet of geraniums',
    'with a cheerful outlook',
    'holding a bouquet of marigolds',
    'wearing a silk ribbon',
    'holding a bouquet of irises',
    'with a warm smile',
    'holding a bouquet of pansies',
    'wearing a velvet cape',
    'holding a bouquet of zinnias',
    'with a bright demeanor',
    'holding a bouquet of chrysanthemums',
    'wearing a floral kimono',
    'holding a bouquet of carnations',
    'with a serene smile',
    'holding a bouquet of hydrangeas',
    'wearing a fringed shawl',
    'holding a bouquet of begonias',
    'with an elegant presence',
    'holding a bouquet of delphiniums',
    'wearing a bohemian dress',
    'holding a bouquet of foxgloves',
    'with a peaceful expression',
    'holding a bouquet of freesias',
    'wearing a tie-dye shirt',
    'holding a bouquet of lilacs',
    'with a joyful heart',
    'holding a bouquet of narcissus',
    'wearing a crochet top',
    'holding a bouquet of violets',
    'with a content heart',
    'holding a bouquet of asters',
    'wearing a sequin dress',
    'holding a bouquet of snapdragons',
    'with a gentle smile',
    'holding a bouquet of sweet peas',
    'wearing a floral mask',
    'holding a bouquet of wisteria',
    'with a blissful expression',
    'holding a bouquet of yarrow',
    'wearing a flower crown with wildflowers',
    'holding a bouquet of daisies and sunflowers',
    'with a luminous smile',
    'holding a bouquet of tulips and roses',
    'wearing a handmade necklace',
    'holding a bouquet of gardenias',
    'with an angelic presence',
    'holding a bouquet of lilies and orchids',
    'wearing a silk ribbon headband',
    'holding a bouquet of peonies and hydrangeas',
    'with a mesmerizing gaze',
    'holding a bouquet of mixed wildflowers',
    'wearing a floral patterned scarf',
    'holding a bouquet of roses and daisies',
    'with an enchanting smile',
    'holding a bouquet of assorted blossoms',
    'wearing a floral embellished jacket',
    'holding a bouquet of seasonal flowers',
    'with a radiant aura',
    'holding a bouquet of exotic flowers',
    'wearing a flower-adorned hat',
    'holding a bouquet of vibrant blooms',
    'with a captivating presence',
    'holding a bouquet of pastel flowers',
    'wearing a floral print dress',
    'holding a bouquet of colorful blossoms',
    'with a delightful expression',
    'holding a bouquet of fragrant flowers',
    'wearing a flower-patterned blouse',
    'holding a bouquet of fresh flowers',
    'with a charming demeanor',
    'holding a bouquet of bright flowers',
    'wearing a floral headband',
    'holding a bouquet of blossoming flowers'
];

const extraList2 = [
    'standing near a fountain',
    'with a backdrop of mountains',
    'under a starry sky',
    'next to a vintage car',
    'next to a cyber car',
    'next to a sports car',
    'next to a rocket ship',
    'next to a space ship',
    'holding a bouquet of roses',
    'holding a bouquet of black roses',
    'escorting the moon king who has a head that is the moon and wears he a nice suit',
    'with an alien',
    'with an NPC',
    'with a random character from any random movie or show or book or comic or song of random choice',
    'standing beside a lighthouse',
    'next to a futuristic motorcycle',
    'with a holographic display',
    'standing in front of a waterfall',
    'next to a classic sailboat',
    'under a rainbow',
    'standing on a bridge at dusk',
    'next to a vintage bicycle',
    'with a glowing aura',
    'standing amidst cherry blossoms',
    'next to a hot air balloon',
    'with a dragon',
    'standing in a bustling marketplace',
    'next to a giant tree',
    'with a unicorn',
    'standing on a cliff overlooking the sea',
    'next to a medieval castle',
    'with a phoenix',
    'standing in a futuristic cityscape',
    'next to a giant robot',
    'with a griffin',
    'standing in a sunflower field',
    'next to a steam locomotive',
    'with a mermaid',
    'standing in an enchanted forest',
    'next to a crystal cave',
    'with a fairy',
    'standing in front of a grand cathedral',
    'next to a vintage airplane',
    'with a centaur',
    'standing on a rooftop at night',
    'next to a spaceship hangar',
    'with a satyr',
    'standing in a desert oasis',
    'next to a robotic arm',
    'with a minotaur',
    'standing beside a bonfire',
    'next to a floating island',
    'with a harpy',
    'standing on a glacier',
    'next to a submarine',
    'with a leviathan',
    'standing in a neon-lit alley',
    'next to a time machine',
    'with a banshee',
    'standing in a twilight meadow',
    'next to a teleportation portal',
    'with a siren',
    'standing beside an ancient statue',
    'next to a flying car',
    'with a gorgon',
    'standing in a futuristic laboratory',
    'next to a monorail',
    'with a werewolf',
    'standing in a misty valley',
    'next to a hoverboard',
    'with a vampire',
    'standing in a vibrant bazaar',
    'next to a hovercraft',
    'with a ghost',
    'standing in an abandoned amusement park',
    'next to a mech suit',
    'with a zombie',
    'standing in a high-tech observatory',
    'next to a jetpack',
    'with a cyborg',
    'standing in a magical library',
    'next to a robotic pet',
    'with a sorcerer',
    'standing on a spaceship deck',
    'next to a digital billboard',
    'with a wizard',
    'standing in a crystalline cavern',
    'next to a levitating platform',
    'with a ninja',
    'standing in an ethereal garden',
    'next to a virtual reality headset',
    'with a samurai',
    'standing in a solar observatory',
    'next to an energy shield',
    'with a pirate',
    'standing in a holographic theater',
    'next to a drone',
    'with a gladiator',
    'standing in a robotic assembly line',
    'next to a nanobot swarm',
    'with an angel',
    'standing in a digital forest',
    'next to a plasma cannon',
    'with a demon',
    'standing in a floating city',
    'next to a quantum computer',
    'with a druid',
    'standing in a celestial observatory',
    'next to a gravity generator',
    'with a bard',
    'standing in a mech battlefield',
    'next to a teleport device',
    'with a monk',
    'standing in a cybernetic dojo',
    'next to a fusion reactor',
    'with a cleric',
    'standing in a data stream',
    'next to a hologram projector',
    'with a paladin',
    'standing in a virtual reality garden',
    'next to an AI companion',
    'with a ranger',
    'standing in a techno-organic forest',
    'next to a bio-engineered creature',
    'with a warlock',
    'standing in a nanotech lab',
    'next to a synthetic landscape',
    'with a necromancer',
    'standing in a futuristic amphitheater',
    'next to an autonomous drone',
    'with a drake',
    'standing in an augmented reality plaza',
    'next to a holographic map',
    'with a griffin',
    'standing in a quantum realm',
    'next to a holographic avatar',
    'with a kitsune',
    'standing in a biomechanical structure',
    'next to a virtual pet',
    'with a phoenix',
    'standing in a photonic garden',
    'next to a cybernetic tree',
    'with a centaur',
    'standing in an energy field',
    'next to a plasma sphere',
    'with a merfolk',
    'standing in a light tunnel',
    'next to a holographic display',
    'with a dragonkin',
    'standing in a data nexus',
    'next to an energy vortex',
    'with a fae',
    'standing in a holographic arena',
    'next to a quantum gateway',
    'with a sylph',
    'standing in a digital temple',
    'next to a cyber nexus',
    'with a sylvan spirit',
    'standing in a virtual gallery',
    'next to an AI construct',
    'with a kitsune spirit',
    'standing in a synthetic sanctuary',
    'next to a holographic guardian',
    'with a nebula spirit',
    'standing in a light-synthesized garden',
    'next to a cybernetic portal',
    'with a starborn entity',
    'standing in a technomagic chamber',
    'next to a holographic oracle',
    'with a celestial being'
];

const extraList3 = [
    'on a cliff',
    'on a bridge',
    'on top of a skyscraper',
    'during sunset',
    'with wind-swept hair',
    'on a sandy beach',
    'amidst falling leaves',
    'in a bustling cityscape',
    'in a neon moon setting',
    'under the cyber sun',
    'on the moon',
    'in a movie',
    'as a movie poster',
    'as a box cover',
    'at dawn',
    'during twilight',
    'under a full moon',
    'in the pouring rain',
    'amidst blooming flowers',
    'in a snowy landscape',
    'during a thunderstorm',
    'in a foggy forest',
    'under the northern lights',
    'on a tropical island',
    'in a desert oasis',
    'amidst towering skyscrapers',
    'in a quiet meadow',
    'under a cherry blossom tree',
    'on a misty morning',
    'in a vibrant marketplace',
    'amidst ancient ruins',
    'on a rooftop garden',
    'during a meteor shower',
    'in a futuristic skyline',
    'on a hidden waterfall',
    'amidst swirling sandstorms',
    'in a tranquil pond',
    'on a rocky shoreline',
    'under a cascading waterfall',
    'in a haunted mansion',
    'amidst colorful graffiti',
    'on a bustling train station',
    'in a serene monastery',
    'under a canopy of stars',
    'in a mystical cave',
    'on a vibrant coral reef',
    'amidst towering redwoods',
    'in an abandoned factory',
    'on a floating dock',
    'under a glowing sunset',
    'in a magical glade',
    'amidst colorful autumn foliage',
    'on a serene lakeside',
    'in a busy airport terminal',
    'under a glowing cityscape',
    'in a sprawling vineyard',
    'on a busy subway platform',
    'amidst a fireworks display',
    'in a tranquil Zen garden',
    'on a vibrant street festival',
    'under a futuristic bridge',
    'in a dense bamboo forest',
    'on a crystal-clear lake',
    'amidst towering icebergs',
    'in a bustling harbor',
    'on a remote mountain peak',
    'under a cascading light show',
    'in a hidden alleyway',
    'on a golden wheat field',
    'amidst a lush jungle',
    'in a minimalist art gallery',
    'on a panoramic viewpoint',
    'under a star-lit canopy',
    'in a high-tech laboratory',
    'on a snowy mountain path',
    'amidst a blooming orchard',
    'in a grand ballroom',
    'on a rustic wooden dock',
    'under a bridge at night',
    'in a sunlit greenhouse',
    'on a windy dune',
    'amidst a bustling street market',
    'in a serene beach cove',
    'on a tranquil island shore',
    'under a moonlit sky',
    'in a colorful carnival',
    'on a majestic waterfall',
    'amidst a snowy forest',
    'in a vibrant urban park',
    'on a scenic overlook',
    'under a rainbow',
    'in a modern art museum',
    'on a historic cobblestone street',
    'amidst blooming tulips',
    'in a cozy cabin',
    'on a quiet country road',
    'under a twilight sky',
    'in a lively concert venue',
    'on a peaceful riverside',
    'amidst towering skyscrapers at night',
    'in a sun-drenched canyon',
    'on a picturesque pier',
    'under a starlit galaxy',
    'in a mystical enchanted forest',
    'on a serene mountain ridge',
    'amidst a vibrant city park',
    'in a luxurious penthouse',
    'on a rustic barn rooftop',
    'under a glowing streetlamp',
    'in a bustling shopping district',
    'on a tranquil mountain lake',
    'amidst a bustling construction site',
    'in a serene public garden',
    'on a hidden garden path',
    'under a glittering fireworks sky',
    'in a quiet suburban neighborhood',
    'on a scenic mountain trail',
    'amidst a vibrant summer festival',
    'in a peaceful countryside meadow',
    'on a sunlit veranda',
    'under a shimmering aurora',
    'in a futuristic neon-lit alley',
    'on a historic landmark site',
    'amidst a tranquil zen pond',
    'in a lively street parade',
    'on a secluded beach at twilight',
    'under a cascading waterfall',
    'in a bustling tech hub',
    'on a scenic lakeside promenade',
    'amidst a vibrant autumn landscape',
    'in a quiet forest clearing',
    'on a bustling urban rooftop',
    'under a radiant sunrise',
    'in a modern high-rise apartment',
    'on a vibrant flower meadow',
    'amidst a colorful sunrise',
    'in a serene botanical garden',
    'on a peaceful lakeshore',
    'under a celestial sky',
    'in a dynamic urban plaza',
    'on a picturesque mountain view',
    'amidst a sparkling city skyline',
    'in a lush tropical rainforest',
    'on a secluded garden bench',
    'under a dazzling light installation',
    'in a quiet moonlit garden',
    'on a bustling city sidewalk',
    'amidst a dreamy twilight haze',
    'in a vibrant street art scene',
    'on a tranquil desert landscape',
    'under a vivid sunset sky',
    'in a lively outdoor concert',
    'on a scenic hilltop',
    'amidst a colorful night market',
    'in a peaceful riverside park',
    'on a bustling urban street',
    'under a radiant daylight sky',
    'in a serene lakeside cabin',
    'on a picturesque seaside cliff',
    'amidst a lush green valley',
    'in a vibrant metropolitan area',
    'on a tranquil forest path',
    'under a majestic mountain range',
    'in a dynamic city center',
    'on a scenic coastal road',
    'amidst a lively urban environment',
    'in a peaceful sunset field',
    'on a historic stone bridge',
    'under a clear blue sky',
    'in a bustling city square',
    'on a quiet woodland trail',
    'amidst a colorful autumn sunset',
    'in a modern downtown area',
    'on a scenic lakeside dock',
    'under a starlit night sky',
    'in a vibrant city nightlife',
    'on a tranquil forest floor',
    'amidst a serene sunrise landscape',
    'in a lively downtown street',
    'on a picturesque riverside park',
    'under a golden sunset glow',
    'in a bustling urban neighborhood',
    'on a peaceful mountain trail',
    'amidst a vibrant floral garden',
    'in a tranquil riverside scene',
    'on a scenic hill overlooking the city',
    'under a sparkling starry night',
    'in a lively city waterfront',
    'on a serene lakeside beach'
];

const extraList4 = [
    'in watercolor style',
    'with vibrant colors',
    'soft focus effect',
    'black and white theme',
    'with a bokeh background',
    'there are two girls',
    'there are three girls',
    'there are 4 girls',
    'there are 5 girls',
    'in oil painting style',
    'with pastel hues',
    'high contrast lighting',
    'with a shallow depth of field',
    'in sepia tones',
    'with a vintage filter',
    'in a minimalist style',
    'with abstract elements',
    'in a surreal style',
    'with geometric patterns',
    'in a pop art style',
    'with a gradient background',
    'in a hyper-realistic style',
    'with a sketch-like quality',
    'in a cartoon style',
    'with a double exposure effect',
    'in a pixel art style',
    'with a vintage vignette',
    'in a matte finish',
    'with a glossy overlay',
    'in a charcoal drawing style',
    'with dynamic shadows',
    'in a stained glass style',
    'with metallic highlights',
    'in a futuristic design',
    'with ethereal lighting',
    'in a flat design style',
    'with a neon glow',
    'in a retro 80s style',
    'with a cinematic filter',
    'in a cubist style',
    'with a holographic effect',
    'in a photorealistic style',
    'with a glitch art effect',
    'in a digital painting style',
    'with an impressionist touch',
    'in a vector art style',
    'with a low-poly aesthetic',
    'in a manga style',
    'with a vaporwave theme',
    'in a steampunk style',
    'with a glitchy background',
    'in a collage style',
    'with a hand-drawn effect',
    'in a 3D render style',
    'with a watercolor wash',
    'in a flat illustration style',
    'with a dreamy overlay',
    'in a pixelated style',
    'with a noir aesthetic',
    'in a hyper-color style',
    'with a grunge texture',
    'in a minimalist black and white',
    'with a vibrant gradient',
    'in a holographic color scheme',
    'with a retro color palette',
    'in a monochromatic scheme',
    'with a colorful mosaic background',
    'in a high saturation style',
    'with a muted color scheme',
    'in a psychedelic style',
    'with a metallic sheen',
    'in a dynamic brushstroke style',
    'with an oil texture overlay',
    'in a minimalist pastel style',
    'with a glossy sheen',
    'in a pastel watercolor style',
    'with a bold color splash',
    'in a schematic line art style',
    'with a soft pastel palette',
    'in a vibrant comic style',
    'with a dynamic lighting effect',
    'in a retro-futuristic style',
    'with an abstract watercolor background',
    'in a neon retro style',
    'with a sepia-toned overlay',
    'in a fragmented cubist style',
    'with a vibrant mosaic effect',
    'in a dark fantasy style',
    'with a luminous glow',
    'in a botanical illustration style',
    'with a watercolor and ink blend',
    'in a vibrant street art style',
    'with a soft pastel wash',
    'in a graphic novel style',
    'with a stained glass background',
    'in a vivid expressionist style',
    'with a monochrome bokeh effect',
    'in a ethereal watercolor style',
    'with a futuristic hologram overlay',
    'in a bright pop color scheme',
    'with a pastel gradient background',
    'in a shadow play style',
    'with a surrealistic color palette',
    'in a traditional Japanese art style',
    'with a retro film grain effect',
    'in a vibrant graffiti style',
    'with a digital glitch overlay',
    'in a fantasy illustration style',
    'with a soft focus glow',
    'in a vibrant oil paint style',
    'with a muted watercolor wash',
    'in a bright vector art style',
    'with a dark monochrome theme',
    'in a colorful mosaic style',
    'with a pastel bokeh effect',
    'in a stylized pop art approach',
    'with a glowing neon background',
    'in a detailed sketch style',
    'with a high-key lighting effect',
    'in a low-key shadow style',
    'with a vibrant and dynamic color scheme',
    'in a modern abstract style',
    'with a soft ambient glow',
    'in a bright and colorful vector style',
    'with a textured watercolor background',
    'in a detailed line art style',
    'with a vibrant light trail effect',
    'in a ethereal dreamscape style',
    'with a dynamic color overlay',
    'in a stylized minimalist approach',
    'with a vibrant and colorful bokeh background',
    'in a rich oil painting style',
    'with a soft pastel lighting',
    'in a bright and lively street art style',
    'with a glowing aurora effect',
    'in a detailed illustrative style',
    'with a vibrant and saturated color palette',
    'in a soft and dreamy watercolor style',
    'with a bold and graphic design',
    'in a dynamic and colorful abstract style',
    'with a shimmering light effect',
    'in a detailed and textured style',
    'with a vibrant and energetic background',
    'in a smooth and flowing watercolor style',
    'with a multi-colored gradient overlay',
    'in a vivid and expressive painting style',
    'with a soft and glowing highlight',
    'in a vibrant and playful illustration style',
    'with a rich and deep color scheme',
    'in a detailed and realistic style',
    'with a dynamic and lively color splash',
    'in a soft and muted pastel style',
    'with a vibrant and bright light effect',
    'in a colorful and abstract expressionist style',
    'with a glowing and luminous background',
    'in a detailed and intricate design style',
    'with a vibrant and cheerful color palette',
    'in a smooth and glossy illustration style',
    'with a bright and sparkling light effect',
    'in a dynamic and bold graphic style',
    'with a rich and vibrant watercolor overlay',
    'in a detailed and expressive painting style',
    'with a soft and subtle color wash',
    'in a vivid and dynamic art style',
    'with a bright and colorful light trail',
    'in a smooth and flowing abstract style',
    'with a shimmering and sparkling effect',
    'in a rich and textured painting style',
    'with a vibrant and lively color overlay',
    'in a detailed and colorful illustration style',
    'with a soft and dreamy glow',
    'in a vibrant and energetic art style',
    'with a bright and saturated light effect',
    'in a dynamic and colorful illustration style',
    'with a rich and deep watercolor background',
    'in a smooth and vibrant graphic style',
    'with a shimmering and luminous light overlay'
];

const extraList5 = [
    'photorealism',
    'highly detailed',
    'in anime style',
    'surreal atmosphere',
    'art deco influence',
    'cyberpunk elements',
    'photorealistic',
    '8-bit pixel style',
    '80s retro film style',
    'retrowave style',
    'darksynth style',
    'in a fantasy art style',
    'with a steampunk aesthetic',
    'in a minimalistic design',
    'with a gothic theme',
    'in a watercolor painting style',
    'with a neon color palette',
    'in a vector illustration style',
    'with a pop art influence',
    'in a manga-inspired style',
    'with a noir cinematic look',
    'in a vaporwave aesthetic',
    'with a pastel color scheme',
    'in a flat design style',
    'with a retro-futuristic vibe',
    'in a high-contrast black and white style',
    'with a bokeh light effect',
    'in a modern abstract style',
    'with a glitch art overlay',
    'in a detailed line art style',
    'with a sepia-toned filter',
    'in a bright and colorful style',
    'with an oil painting texture',
    'in a digital matte painting style',
    'with a holographic effect',
    'in a charcoal drawing style',
    'with a mosaic pattern',
    'in a stained glass style',
    'with a dynamic brushstroke effect',
    'in a low-poly 3D style',
    'with a hand-drawn sketch feel',
    'in a pixel art landscape',
    'with a holographic sheen',
    'in a dynamic comic book style',
    'with a rich oil texture',
    'in a detailed fantasy illustration',
    'with a vibrant graffiti look',
    'in a minimalistic monochrome style',
    'with a retro pixelated effect',
    'in a glossy digital art style',
    'with a vibrant gradient overlay',
    'in a high-definition realism style',
    'with a psychedelic color scheme',
    'in a soft pastel illustration style',
    'with a metallic sheen',
    'in a vibrant expressionist style',
    'with a digital glitch effect',
    'in a textured watercolor style',
    'with a monochrome color palette',
    'in a vibrant street art style',
    'with a digital painting finish',
    'in a dreamy soft-focus style',
    'with a dynamic vector graphic look',
    'in a traditional oil painting style',
    'with a layered collage effect',
    'in a stylized pop culture style',
    'with a retro arcade aesthetic',
    'in a bold and graphic style',
    'with a detailed architectural design',
    'in a high-saturation color style',
    'with a luminous glow effect',
    'in a dynamic action illustration style',
    'with a sophisticated art nouveau influence',
    'in a crisp and clean vector style',
    'with a vibrant and colorful overlay',
    'in a classic renaissance painting style',
    'with a soft watercolor wash',
    'in a textured mixed media style',
    'with a sharp digital clarity',
    'in a romantic impressionist style',
    'with a vibrant and energetic design',
    'in a dreamy ethereal style',
    'with a detailed and intricate pattern',
    'in a bold minimalist style',
    'with a rich and deep color scheme',
    'in a bright and cheerful illustration style',
    'with a dark and moody atmosphere',
    'in a dynamic and vibrant style',
    'with a futuristic digital aesthetic',
    'in a soft and muted color palette',
    'with a detailed and realistic rendering',
    'in a playful cartoon style',
    'with a vibrant and eclectic mix of colors',
    'in a high-fidelity digital art style',
    'with a gritty urban texture',
    'in a sleek modern design',
    'with a soft and glowing light effect',
    'in a highly stylized illustration style',
    'with a dramatic chiaroscuro lighting',
    'in a richly textured art style',
    'with a bright and sunny color palette',
    'in a cool-toned digital painting style',
    'with a warm and inviting atmosphere',
    'in a highly abstract art style',
    'with a vibrant and dynamic brushwork',
    'in a clean and minimalist vector style',
    'with a colorful and lively composition',
    'in a detailed architectural illustration style',
    'with a soft and dreamy focus',
    'in a bold and expressive art style',
    'with a radiant and luminous color scheme',
    'in a highly detailed 3D render style',
    'with a vivid and saturated color palette',
    'in a classic oil painting technique',
    'with a smooth and polished finish',
    'in a vibrant and energetic digital art style',
    'with a soft and subtle color overlay',
    'in a dynamic and fluid illustration style',
    'with a rich and harmonious color harmony',
    'in a sophisticated and elegant art style',
    'with a bright and bold color splash',
    'in a smooth and flowing digital painting style',
    'with a detailed and lifelike texture',
    'in a playful and whimsical illustration style',
    'with a cool and calming color palette',
    'in a vibrant and intricate mosaic style',
    'with a warm and earthy tone',
    'in a dynamic and action-packed art style',
    'with a rich and layered color scheme',
    'in a clean and sharp vector illustration style',
    'with a vibrant and colorful digital overlay',
    'in a detailed and ornate art style',
    'with a soft and natural lighting effect',
    'in a highly realistic digital painting style',
    'with a bold and striking color contrast',
    'in a smooth and refined illustration style',
    'with a bright and lively color explosion',
    'in a highly stylized cartoon style',
    'with a vibrant and expressive brushstroke',
    'in a detailed and realistic oil painting style',
    'with a soft and diffused light effect',
    'in a dynamic and energetic art style',
    'with a vibrant and intense color palette',
    'in a sleek and modern digital illustration style',
    'with a detailed and precise linework',
    'in a vivid and bright watercolor style',
    'with a rich and deep tonal range',
    'in a playful and colorful comic style',
    'with a smooth and glossy digital finish',
    'in a highly abstract digital art style',
    'with a dynamic and fluid brushstroke effect',
    'in a richly detailed fantasy art style',
    'with a vibrant and dynamic color infusion',
    'in a clean and modern graphic style',
    'with a shimmering glow effect',
    'in a detailed and intricate design style',
    'with a vibrant and cheerful color palette',
    'in a smooth and glossy illustration style',
    'with a bright and sparkling light effect',
    'in a dynamic and bold graphic style',
    'with a rich oil texture',
    'in a detailed fantasy illustration',
    'with a vibrant graffiti look',
    'in a minimalistic monochrome style',
    'with a retro pixelated effect',
    'in a glossy digital art style',
    'with a vibrant gradient overlay',
    'in a high-definition realism style',
    'with a psychedelic color scheme',
    'in a soft pastel illustration style',
    'with a metallic sheen',
    'in a vibrant expressionist style',
    'with a digital glitch effect',
    'in a textured watercolor style',
    'with a monochrome color palette',
    'in a vibrant street art style',
    'with a digital painting finish',
    'in a dreamy soft-focus style',
    'with a dynamic vector graphic look',
    'in a traditional oil painting style',
    'with a layered collage effect',
    'in a stylized pop culture style',
    'with a retro arcade aesthetic',
    'in a bold and graphic style',
    'with a detailed architectural design',
    'in a high-saturation style',
    'with a luminous glow effect',
    'in a dynamic action illustration style',
    'with a sophisticated art nouveau influence',
    'in a crisp and clean vector style',
    'with a vibrant and dynamic color scheme',
    'in a classic renaissance painting style',
    'with a soft watercolor wash',
    'in a textured mixed media style',
    'with a sharp digital clarity',
    'in a romantic impressionist style',
    'with a vibrant and energetic design',
    'in a dreamy ethereal style',
    'with a detailed and intricate pattern',
    'in a bold minimalist style',
    'with a rich and deep color scheme',
    'in a bright and cheerful illustration style',
    'with a dark and moody atmosphere',
    'in a dynamic and vibrant style',
    'with a futuristic digital aesthetic',
    'in a soft and muted color palette',
    'with a detailed and realistic rendering',
    'in a playful cartoon style',
    'with a vibrant and eclectic mix of colors',
    'in a high-fidelity digital art style',
    'with a gritty urban texture',
    'in a sleek modern design',
    'with a soft and glowing light effect',
    'in a highly stylized illustration style',
    'with a dramatic chiaroscuro lighting',
    'in a richly textured art style',
    'with a bright and sunny color palette',
    'in a cool-toned digital painting style',
    'with a warm and inviting atmosphere',
    'in a highly abstract art style',
    'with a vibrant and dynamic brushwork',
    'in a clean and minimalist vector style',
    'with a vibrant and colorful composition',
    'in a detailed architectural illustration style',
    'with a soft and dreamy focus',
    'in a bold and expressive art style',
    'with a radiant and luminous color scheme',
    'in a highly detailed 3D render style',
    'with a vivid and saturated color palette',
    'in a classic oil painting technique',
    'with a smooth and polished finish',
    'in a vibrant and energetic digital art style',
    'with a soft and subtle color overlay',
    'in a dynamic and fluid illustration style',
    'with a rich and harmonious color harmony',
    'in a sophisticated and elegant art style',
    'with a bright and bold color splash',
    'in a smooth and flowing digital painting style',
    'with a detailed and lifelike texture',
    'in a playful and whimsical illustration style',
    'with a cool and calming color palette',
    'in a vibrant and intricate mosaic style',
    'with a warm and earthy tone',
    'in a dynamic and action-packed art style',
    'with a rich and layered color scheme',
    'in a clean and sharp vector illustration style',
    'with a vibrant and colorful digital overlay',
    'in a detailed and ornate art style',
    'with a soft and natural lighting effect',
    'in a highly realistic digital painting style',
    'with a bold and striking color contrast',
    'in a smooth and refined illustration style',
    'with a bright and lively color explosion',
    'in a highly stylized cartoon style',
    'with a vibrant and expressive brushstroke',
    'in a detailed and realistic oil painting style',
    'with a soft and diffused light effect',
    'in a dynamic and energetic art style',
    'with a vibrant and intense color palette',
    'in a sleek and modern digital illustration style',
    'with a detailed and precise linework',
    'in a vivid and bright watercolor style',
    'with a rich and deep tonal range',
    'in a playful and colorful comic style',
    'with a smooth and glossy digital finish',
    'in a highly abstract digital art style',
    'with a dynamic and fluid brushstroke effect',
    'in a richly detailed fantasy art style',
    'with a vibrant and dynamic color infusion',
    'in a clean and modern graphic style',
    'with a shimmering glow effect',
    'in a detailed and intricate design style',
    'with a vibrant and cheerful color palette',
    'in a smooth and glossy illustration style',
    'with a bright and sparkling light effect',
    'in a dynamic and bold graphic style',
    'with a rich oil texture',
    'in a detailed fantasy illustration',
    'with a vibrant graffiti look',
    'in a minimalistic monochrome style',
    'with a retro pixelated effect',
    'in a glossy digital art style',
    'with a vibrant gradient overlay',
    'in a high-definition realism style',
    'with a psychedelic color scheme',
    'in a soft pastel illustration style',
    'with a metallic sheen',
    'in a vibrant expressionist style',
    'with a digital glitch effect',
    'in a textured watercolor style',
    'with a monochrome color palette',
    'in a vibrant street art style',
    'with a digital painting finish',
    'in a dreamy soft-focus style',
    'with a dynamic vector graphic look',
    'in a traditional oil painting style',
    'with a layered collage effect',
    'in a stylized pop culture style',
    'with a retro arcade aesthetic',
    'in a bold and graphic style',
    'with a detailed architectural design',
    'in a high-saturation style',
    'with a luminous glow effect',
    'in a dynamic action illustration style',
    'with a sophisticated art nouveau influence',
    'in a crisp and clean vector style',
    'with a vibrant and dynamic color scheme',
    'in a classic renaissance painting style',
    'with a soft watercolor wash',
    'in a textured mixed media style',
    'with a sharp digital clarity',
    'in a romantic impressionist style',
    'with a vibrant and energetic design',
    'in a dreamy ethereal style',
    'with a detailed and intricate pattern',
    'in a bold minimalist style',
    'with a rich and deep color scheme',
    'in a bright and cheerful illustration style',
    'with a dark and moody atmosphere',
    'in a dynamic and vibrant style',
    'with a futuristic digital aesthetic',
    'in a soft and muted color palette',
    'with a detailed and realistic rendering',
    'in a playful cartoon style',
    'with a vibrant and eclectic mix of colors',
    'in a high-fidelity digital art style',
    'with a gritty urban texture',
    'in a sleek modern design',
    'with a soft and glowing light effect',
    'in a highly stylized illustration style',
    'with a dramatic chiaroscuro lighting',
    'in a richly textured art style',
    'with a bright and sunny color palette',
    'in a cool-toned digital painting style',
    'with a warm and inviting atmosphere',
    'in a highly abstract art style',
    'with a vibrant and dynamic brushwork',
    'in a clean and minimalist vector style',
    'with a vibrant and colorful composition',
    'in a detailed architectural illustration style',
    'with a soft and dreamy focus',
    'in a bold and expressive art style',
    'with a radiant and luminous color scheme',
    'in a highly detailed 3D render style',
    'with a vivid and saturated color palette',
    'in a classic oil painting technique',
    'with a smooth and polished finish',
    'in a vibrant and energetic digital art style',
    'with a soft and subtle color overlay',
    'in a dynamic and fluid illustration style',
    'with a rich and harmonious color harmony',
    'in a sophisticated and elegant art style',
    'with a bright and bold color splash',
    'in a smooth and flowing digital painting style',
    'with a detailed and lifelike texture',
    'in a playful and whimsical illustration style',
    'with a cool and calming color palette',
    'in a vibrant and intricate mosaic style',
    'with a warm and earthy tone',
    'in a dynamic and action-packed art style',
    'with a rich and layered color scheme',
    'in a clean and sharp vector illustration style',
    'with a vibrant and colorful digital overlay',
    'in a detailed and ornate art style',
    'with a soft and natural lighting effect',
    'in a highly realistic digital painting style',
    'with a bold and striking color contrast',
    'in a smooth and refined illustration style',
    'with a bright and lively color explosion',
    'in a highly stylized cartoon style',
    'with a vibrant and expressive brushstroke',
    'in a detailed and realistic oil painting style',
    'with a soft and diffused light effect',
    'in a dynamic and energetic art style',
    'with a vibrant and intense color palette',
    'in a sleek and modern digital illustration style',
    'with a detailed and precise linework',
    'in a vivid and bright watercolor style',
    'with a rich and deep tonal range',
    'in a playful and colorful comic style',
    'with a smooth and glossy digital finish',
    'in a highly abstract digital art style',
    'with a dynamic and fluid brushstroke effect',
    'in a richly detailed fantasy art style',
    'with a vibrant and dynamic color infusion',
    'in a clean and modern graphic style',
    'with a shimmering glow effect',
    'in a detailed and intricate design style',
    'with a vibrant and cheerful color palette',
    'in a smooth and glossy illustration style',
    'with a bright and sparkling light effect',
    'in a dynamic and bold graphic style',
    'with a rich oil texture',
    'in a detailed fantasy illustration',
    'with a vibrant graffiti look',
    'in a minimalistic monochrome style',
    'with a retro pixelated effect',
    'in a glossy digital art style',
    'with a vibrant gradient overlay',
    'in a high-definition realism style',
    'with a psychedelic color scheme',
    'in a soft pastel illustration style',
    'with a metallic sheen',
    'in a vibrant expressionist style',
    'with a digital glitch effect',
    'in a textured watercolor style',
    'with a monochrome color palette',
    'in a vibrant street art style',
    'with a digital painting finish',
    'in a dreamy soft-focus style',
    'with a dynamic vector graphic look',
    'in a traditional oil painting style',
    'with a layered collage effect',
    'in a stylized pop culture style',
    'with a retro arcade aesthetic',
    'in a bold and graphic style',
    'with a detailed architectural design',
    'in a high-saturation style',
    'with a luminous glow effect',
    'in a dynamic action illustration style',
    'with a sophisticated art nouveau influence',
    'in a crisp and clean vector style',
    'with a vibrant and dynamic color scheme',
    'in a classic renaissance painting style',
    'with a soft watercolor wash',
    'in a textured mixed media style',
    'with a sharp digital clarity',
    'in a romantic impressionist style',
    'with a vibrant and energetic design',
    'in a dreamy ethereal style',
    'with a detailed and intricate pattern',
    'in a bold minimalist style',
    'with a rich and deep color scheme',
    'in a bright and cheerful illustration style',
    'with a dark and moody atmosphere',
    'in a dynamic and vibrant style',
    'with a futuristic digital aesthetic',
    'in a soft and muted color palette',
    'with a detailed and realistic rendering',
    'in a playful cartoon style',
    'with a vibrant and eclectic mix of colors',
    'in a high-fidelity digital art style',
    'with a gritty urban texture',
    'in a sleek modern design',
    'with a soft and glowing light effect',
    'in a highly stylized illustration style',
    'with a dramatic chiaroscuro lighting',
    'in a richly textured art style',
    'with a bright and sunny color palette',
    'in a cool-toned digital painting style',
    'with a warm and inviting atmosphere',
    'in a highly abstract art style',
    'with a vibrant and dynamic brushwork',
    'in a clean and minimalist vector style',
    'with a vibrant and colorful composition',
    'in a detailed architectural illustration style',
    'with a soft and dreamy focus',
    'in a bold and expressive art style',
    'with a radiant and luminous color scheme',
    'in a highly detailed 3D render style',
    'with a vivid and saturated color palette',
    'in a classic oil painting technique',
    'with a smooth and polished finish',
    'in a vibrant and energetic digital art style',
    'with a soft and subtle color overlay',
    'in a dynamic and fluid illustration style',
    'with a rich and harmonious color harmony',
    'in a sophisticated and elegant art style',
    'with a bright and bold color splash',
    'in a smooth and flowing digital painting style',
    'with a detailed and lifelike texture',
    'in a playful and whimsical illustration style',
    'with a cool and calming color palette',
    'in a vibrant and intricate mosaic style',
    'with a warm and earthy tone',
    'in a dynamic and action-packed art style',
    'with a rich and layered color scheme',
    'in a clean and sharp vector illustration style',
    'with a vibrant and colorful digital overlay',
    'in a detailed and ornate art style',
    'with a soft and natural lighting effect',
    'in a highly realistic digital painting style',
    'with a bold and striking color contrast',
    'in a smooth and refined illustration style',
    'with a bright and lively color explosion',
    'in a highly stylized cartoon style',
    'with a vibrant and expressive brushstroke',
    'in a detailed and realistic oil painting style',
    'with a soft and diffused light effect',
    'in a dynamic and energetic art style',
    'with a vibrant and intense color palette',
    'in a sleek and modern digital illustration style',
    'with a detailed and precise linework',
    'in a vivid and bright watercolor style',
    'with a rich and deep tonal range',
    'in a playful and colorful comic style',
    'with a smooth and glossy digital finish',
    'in a highly abstract digital art style',
    'with a dynamic and fluid brushstroke effect',
    'in a richly detailed fantasy art style',
    'with a vibrant and dynamic color infusion',
    'in a clean and modern graphic style',
    'with a shimmering glow effect',
    'in a detailed and intricate design style',
    'with a vibrant and cheerful color palette',
    'in a smooth and glossy illustration style',
    'with a bright and sparkling light effect',
    'in a dynamic and bold graphic style',
    'with a rich oil texture',
    'in a detailed fantasy illustration',
    'with a vibrant graffiti look',
    'in a minimalistic monochrome style',
    'with a retro pixelated effect',
    'in a glossy digital art style',
    'with a vibrant gradient overlay',
    'in a high-definition realism style',
    'with a psychedelic color scheme',
    'in a soft pastel illustration style',
    'with a metallic sheen',
    'in a vibrant expressionist style',
    'with a digital glitch effect',
    'in a textured watercolor style',
    'with a monochrome color palette',
    'in a vibrant street art style',
    'with a digital painting finish',
    'in a dreamy soft-focus style',
    'with a dynamic vector graphic look',
    'in a traditional oil painting style',
    'with a layered collage effect',
    'in a stylized pop culture style',
    'with a retro arcade aesthetic',
    'in a bold and graphic style',
    'with a detailed architectural design',
    'in a high-saturation style',
    'with a luminous glow effect',
    'in a dynamic action illustration style',
    'with a sophisticated art nouveau influence',
    'in a crisp and clean vector style',
    'with a vibrant and dynamic color scheme',
    'in a classic renaissance painting style',
    'with a soft watercolor wash',
    'in a textured mixed media style',
    'with a sharp digital clarity',
    'in a romantic impressionist style',
    'with a vibrant and energetic design',
    'in a dreamy ethereal style',
    'with a detailed and intricate pattern',
    'in a bold minimalist style',
    'with a rich and deep color scheme',
    'in a bright and cheerful illustration style',
    'with a dark and moody atmosphere',
    'in a dynamic and vibrant style',
    'with a futuristic digital aesthetic',
    'in a soft and muted color palette',
    'with a detailed and realistic rendering',
    'in a playful cartoon style',
    'with a vibrant and eclectic mix of colors',
    'in a high-fidelity digital art style',
    'with a gritty urban texture',
    'in a sleek modern design',
    'with a soft and glowing light effect',
    'in a highly stylized illustration style',
    'with a dramatic chiaroscuro lighting',
    'in a richly textured art style',
    'with a bright and sunny color palette',
    'in a cool-toned digital painting style',
    'with a warm and inviting atmosphere',
    'in a highly abstract art style',
    'with a vibrant and dynamic brushwork',
    'in a clean and minimalist vector style',
    'with a vibrant and colorful composition',
    'in a detailed architectural illustration style',
    'with a soft and dreamy focus',
    'in a bold and expressive art style',
    'with a radiant and luminous color scheme',
    'in a highly detailed 3D render style',
    'with a vivid and saturated color palette',
    'in a classic oil painting technique',
    'with a smooth and polished finish',
    'in a vibrant and energetic digital art style',
    'with a soft and subtle color overlay',
    'in a dynamic and fluid illustration style',
    'with a rich and harmonious color harmony',
    'in a sophisticated and elegant art style',
    'with a bright and bold color splash',
    'in a smooth and flowing digital painting style',
    'with a detailed and lifelike texture',
    'in a playful and whimsical illustration style',
    'with a cool and calming color palette',
    'in a vibrant and intricate mosaic style',
    'with a warm and earthy tone',
    'in a dynamic and action-packed art style',
    'with a rich and layered color scheme',
    'in a clean and sharp vector illustration style',
    'with a vibrant and colorful digital overlay',
    'in a detailed and ornate art style',
    'with a soft and natural lighting effect',
    'in a highly realistic digital painting style',
    'with a bold and striking color contrast',
    'in a smooth and refined illustration style',
    'with a bright and lively color explosion',
    'in a highly stylized cartoon style',
    'with a vibrant and expressive brushstroke',
    'in a detailed and realistic oil painting style',
    'with a soft and diffused light effect',
    'in a dynamic and energetic art style',
    'with a vibrant and intense color palette',
    'in a sleek and modern digital illustration style',
    'with a detailed and precise linework',
    'in a vivid and bright watercolor style',
    'with a rich and deep tonal range',
    'in a playful and colorful comic style',
    'with a smooth and glossy digital finish',
    'in a highly abstract digital art style',
    'with a dynamic and fluid brushstroke effect',
    'in a richly detailed fantasy art style',
    'with a vibrant and dynamic color infusion',
    'in a clean and modern graphic style',
    'with a shimmering glow effect',
    'in a detailed and intricate design style',
    'with a vibrant and cheerful color palette',
    'in a smooth and glossy illustration style',
    'with a bright and sparkling light effect',
    'in a dynamic and bold graphic style',
    'with a rich oil texture',
    'in a detailed fantasy illustration',
    'with a vibrant graffiti look',
    'in a minimalistic monochrome style',
    'with a retro pixelated effect',
    'in a glossy digital art style',
    'with a vibrant gradient overlay',
    'in a high-definition realism style',
    'with a psychedelic color scheme',
    'in a soft pastel illustration style',
    'with a metallic sheen',
    'in a vibrant expressionist style',
    'with a digital glitch effect',
    'in a textured watercolor style',
    'with a monochrome color palette',
    'in a vibrant street art style',
    'with a digital painting finish',
    'in a dreamy soft-focus style',
    'with a dynamic vector graphic look',
    'in a traditional oil painting style',
    'with a layered collage effect',
    'in a stylized pop culture style',
    'with a retro arcade aesthetic',
    'in a bold and graphic style',
    'with a detailed architectural design',
    'in a high-saturation style',
    'with a luminous glow effect',
    'in a dynamic action illustration style',
    'with a sophisticated art nouveau influence',
    'in a crisp and clean vector style',
    'with a vibrant and dynamic color scheme',
    'in a classic renaissance painting style',
    'with a soft watercolor wash',
    'in a textured mixed media style',
    'with a sharp digital clarity',
    'in a romantic impressionist style',
    'with a vibrant and energetic design',
    'in a dreamy ethereal style',
    'with a detailed and intricate pattern',
    'in a bold minimalist style',
    'with a rich and deep color scheme',
    'in a bright and cheerful illustration style',
    'with a dark and moody atmosphere',
    'in a dynamic and vibrant style',
    'with a futuristic digital aesthetic',
    'in a soft and muted color palette',
    'with a detailed and realistic rendering',
    'in a playful cartoon style',
    'with a vibrant and eclectic mix of colors',
    'in a high-fidelity digital art style',
    'with a gritty urban texture',
    'in a sleek modern design',
    'with a soft and glowing light effect',
    'in a highly stylized illustration style',
    'with a dramatic chiaroscuro lighting',
    'in a richly textured art style',
    'with a bright and sunny color palette',
    'in a cool-toned digital painting style',
    'with a warm and inviting atmosphere',
    'in a highly abstract art style',
    'with a vibrant and dynamic brushwork',
    'in a clean and minimalist vector style',
    'with a vibrant and colorful composition',
    'in a detailed architectural illustration style',
    'with a soft and dreamy focus',
    'in a bold and expressive art style',
    'with a radiant and luminous color scheme',
    'in a highly detailed 3D render style',
    'with a vivid and saturated color palette',
    'in a classic oil painting technique',
    'with a smooth and polished finish',
    'in a vibrant and energetic digital art style',
    'with a soft and subtle color overlay',
    'in a dynamic and fluid illustration style',
    'with a rich and harmonious color harmony',
    'in a sophisticated and elegant art style',
    'with a bright and bold color splash',
    'in a smooth and flowing digital painting style',
    'with a detailed and lifelike texture',
    'in a playful and whimsical illustration style',
    'with a cool and calming color palette',
    'in a vibrant and intricate mosaic style',
    'with a warm and earthy tone',
    'in a dynamic and action-packed art style',
    'with a rich and layered color scheme',
    'in a clean and sharp vector illustration style',
    'with a vibrant and colorful digital overlay',
    'in a detailed and ornate art style',
    'with a soft and natural lighting effect',
    'in a highly realistic digital painting style',
    'with a bold and striking color contrast',
    'in a smooth and refined illustration style',
    'with a bright and lively color explosion',
    'in a highly stylized cartoon style',
    'with a vibrant and expressive brushstroke',
    'in a detailed and realistic oil painting style',
    'with a soft and diffused light effect',
    'in a dynamic and energetic art style',
    'with a vibrant and intense color palette',
    'in a sleek and modern digital illustration style',
    'with a detailed and precise linework',
    'in a vivid and bright watercolor style',
    'with a rich and deep tonal range',
    'in a playful and colorful comic style',
    'with a smooth and glossy digital finish',
    'in a highly abstract digital art style',
    'with a dynamic and fluid brushstroke effect',
    'in a richly detailed fantasy art style',
    'with a vibrant and dynamic color infusion',
    'in a clean and modern graphic style',
    'with a shimmering glow effect',
    'in a detailed and intricate design style',
    'with a vibrant and cheerful color palette',
    'in a smooth and glossy illustration style',
    'with a bright and sparkling light effect',
    'in a dynamic and bold graphic style',
    'with a rich oil texture',
    'in a detailed fantasy illustration',
    'with a vibrant graffiti look',
    'in a minimalistic monochrome style',
    'with a retro pixelated effect',
    'in a glossy digital art style',
    'with a vibrant gradient overlay',
    'in a high-definition realism style',
    'with a psychedelic color scheme',
    'in a soft pastel illustration style',
    'with a metallic sheen',
    'in a vibrant expressionist style',
    'with a digital glitch effect',
    'in a textured watercolor style',
    'with a monochrome color palette',
    'in a vibrant street art style',
    'with a digital painting finish',
    'in a dreamy soft-focus style',
    'with a dynamic vector graphic look',
    'in a traditional oil painting style',
    'with a layered collage effect',
    'in a stylized pop culture style',
    'with a retro arcade aesthetic',
    'in a bold and graphic style',
    'with a detailed architectural design',
    'in a high-saturation style',
    'with a luminous glow effect',
    'in a dynamic action illustration style',
    'with a sophisticated art nouveau influence',
    'in a crisp and clean vector style',
    'with a vibrant and dynamic color scheme',
    'in a classic renaissance painting style',
    'with a soft watercolor wash',
    'in a textured mixed media style',
    'with a sharp digital clarity',
    'in a romantic impressionist style',
    'with a vibrant and energetic design',
    'in a dreamy ethereal style',
    'with a detailed and intricate pattern',
    'in a bold minimalist style',
    'with a rich and deep color scheme',
    'in a bright and cheerful illustration style',
    'with a dark and moody atmosphere',
    'in a dynamic and vibrant style',
    'with a futuristic digital aesthetic',
    'in a soft and muted color palette',
    'with a detailed and realistic rendering',
    'in a playful cartoon style',
    'with a vibrant and eclectic mix of colors',
    'in a high-fidelity digital art style',
    'with a gritty urban texture',
    'in a sleek modern design',
    'with a soft and glowing light effect',
    'in a highly stylized illustration style',
    'with a dramatic chiaroscuro lighting',
    'in a richly textured art style',
    'with a bright and sunny color palette',
    'in a cool-toned digital painting style',
    'with a warm and inviting atmosphere',
    'in a highly abstract art style',
    'with a vibrant and dynamic brushwork',
    'in a clean and minimalist vector style',
    'with a vibrant and colorful composition',
    'in a detailed architectural illustration style',
    'with a soft and dreamy focus',
    'in a bold and expressive art style',
    'with a radiant and luminous color scheme',
    'in a highly detailed 3D render style',
    'with a vivid and saturated color palette',
    'in a classic oil painting technique',
    'with a smooth and polished finish',
    'in a vibrant and energetic digital art style',
    'with a soft and subtle color overlay',
    'in a dynamic and fluid illustration style',
    'with a rich and harmonious color harmony',
    'in a sophisticated and elegant art style',
    'with a bright and bold color splash',
    'in a smooth and flowing digital painting style',
    'with a detailed and lifelike texture',
    'in a playful and whimsical illustration style',
    'with a cool and calming color palette',
    'in a vibrant and intricate mosaic style',
    'with a warm and earthy tone',
    'in a dynamic and action-packed art style',
    'with a rich and layered color scheme',
    'in a clean and sharp vector illustration style',
    'with a vibrant and colorful digital overlay',
    'in a detailed and ornate art style',
    'with a soft and natural lighting effect',
    'in a highly realistic digital painting style',
    'with a bold and striking color contrast',
    'in a smooth and refined illustration style',
    'with a bright and lively color explosion',
    'in a highly stylized cartoon style',
    'with a vibrant and expressive brushstroke',
    'in a detailed and realistic oil painting style',
    'with a soft and diffused light effect',
    'in a dynamic and energetic art style',
    'with a vibrant and intense color palette',
    'in a sleek and modern digital illustration style',
    'with a detailed and precise linework',
    'in a vivid and bright watercolor style',
    'with a rich and deep tonal range',
    'in a playful and colorful comic style',
    'with a smooth and glossy digital finish',
    'in a highly abstract digital art style',
    'with a dynamic and fluid brushstroke effect',
    'in a richly detailed fantasy art style',
    'with a vibrant and dynamic color infusion',
    'in a clean and modern graphic style',
    'with a shimmering glow effect',
    'in a detailed and intricate design style',
    'with a vibrant and cheerful color palette',
    'in a smooth and glossy illustration style',
    'with a bright and sparkling light effect',
    'in a dynamic and bold graphic style',
    'with a rich oil texture',
    'in a detailed fantasy illustration',
    'with a vibrant graffiti look',
    'in a minimalistic monochrome style',
    'with a retro pixelated effect',
    'in a glossy digital art style',
    'with a vibrant gradient overlay',
    'in a high-definition realism style',
    'with a psychedelic color scheme',
    'in a soft pastel illustration style',
    'with a metallic sheen',
    'in a vibrant expressionist style',
    'with a digital glitch effect',
    'in a textured watercolor style',
    'with a monochrome color palette',
    'in a vibrant street art style',
    'with a digital painting finish',
    'in a dreamy soft-focus style',
    'with a dynamic vector graphic look',
    'in a traditional oil painting style',
    'with a layered collage effect',
    'in a stylized pop culture style',
    'with a retro arcade aesthetic',
    'in a bold and graphic style',
    'with a detailed architectural design',
    'in a high-saturation style',
    'with a luminous glow effect',
    'in a dynamic action illustration style',
    'with a sophisticated art nouveau influence',
    'in a crisp and clean vector style',
    'with a vibrant and dynamic color scheme',
    'in a classic renaissance painting style',
    'with a soft watercolor wash',
    'in a textured mixed media style',
    'with a sharp digital clarity',
    'in a romantic impressionist style',
    'with a vibrant and energetic design',
    'in a dreamy ethereal style',
    'with a detailed and intricate pattern',
    'in a bold minimalist style',
    'with a rich and deep color scheme',
    'in a bright and cheerful illustration style',
    'with a dark and moody atmosphere',
    'in a dynamic and vibrant style',
    'with a futuristic digital aesthetic',
    'in a soft and muted color palette',
    'with a detailed and realistic rendering',
    'in a playful cartoon style',
    'with a vibrant and eclectic mix of colors',
    'in a high-fidelity digital art style',
    'with a gritty urban texture',
    'in a sleek modern design',
    'with a soft and glowing light effect',
    'in a highly stylized illustration style',
    'with a dramatic chiaroscuro lighting',
    'in a richly textured art style',
    'with a bright and sunny color palette',
    'in a cool-toned digital painting style',
    'with a warm and inviting atmosphere',
    'in a highly abstract art style',
    'with a vibrant and dynamic brushwork',
    'in a clean and minimalist vector style',
    'with a vibrant and colorful composition',
    'in a detailed architectural illustration style',
    'with a soft and dreamy focus',
    'in a bold and expressive art style',
    'with a radiant and luminous color scheme',
    'in a highly detailed 3D render style',
    'with a vivid and saturated color palette',
    'in a classic oil painting technique',
    'with a smooth and polished finish',
    'in a vibrant and energetic digital art style',
    'with a soft and subtle color overlay',
    'in a dynamic and fluid illustration style',
    'with a rich and harmonious color harmony',
    'in a sophisticated and elegant art style',
    'with a bright and bold color splash',
    'in a smooth and flowing digital painting style',
    'with a detailed and lifelike texture',
    'in a playful and whimsical illustration style',
    'with a cool and calming color palette',
    'in a vibrant and intricate mosaic style',
    'with a warm and earthy tone',
    'in a dynamic and action-packed art style',
    'with a rich and layered color scheme',
    'in a clean and sharp vector illustration style',
    'with a vibrant and colorful digital overlay',
    'in a detailed and ornate art style',
    'with a soft and natural lighting effect',
    'in a highly realistic digital painting style',
    'with a bold and striking color contrast',
    'in a smooth and refined illustration style',
    'with a bright and lively color explosion',
    'in a highly stylized cartoon style',
    'with a vibrant and expressive brushstroke',
    'in a detailed and realistic oil painting style',
    'with a soft and diffused light effect',
    'in a dynamic and energetic art style',
    'with a vibrant and intense color palette',
    'in a sleek and modern digital illustration style',
    'with a detailed and precise linework',
    'in a vivid and bright watercolor style',
    'with a rich and deep tonal range',
    'in a playful and colorful comic style',
    'with a smooth and glossy digital finish',
    'in a highly abstract digital art style',
    'with a dynamic and fluid brushstroke effect',
    'in a richly detailed fantasy art style',
    'with a vibrant and dynamic color infusion',
    'in a clean and modern graphic style',
    'with a shimmering glow effect',
    'in a detailed and intricate design style',
    'with a vibrant and cheerful color palette',
    'in a smooth and glossy illustration style',
    'with a bright and sparkling light effect',
    'in a dynamic and bold graphic style',
    'with a rich oil texture',
    'in a detailed fantasy illustration',
    'with a vibrant graffiti look',
    'in a minimalistic monochrome style',
    'with a retro pixelated effect',
    'in a glossy digital art style',
    'with a vibrant gradient overlay',
    'in a high-definition realism style',
    'with a psychedelic color scheme',
    'in a soft pastel illustration style',
    'with a metallic sheen',
    'in a vibrant expressionist style',
    'with a digital glitch effect',
    'in a textured watercolor style',
    'with a monochrome color palette',
    'in a vibrant street art style',
    'with a digital painting finish',
    'in a dreamy soft-focus style',
    'with a dynamic vector graphic look',
    'in a traditional oil painting style',
    'with a layered collage effect',
    'in a stylized pop culture style',
    'with a retro arcade aesthetic',
    'in a bold and graphic style',
    'with a detailed architectural design',
    'in a high-saturation style',
    'with a luminous glow effect',
    'in a dynamic action illustration style',
    'with a sophisticated art nouveau influence',
    'in a crisp and clean vector style',
    'with a vibrant and dynamic color scheme',
    'in a classic renaissance painting style',
    'with a soft watercolor wash',
    'in a textured mixed media style',
    'with a sharp digital clarity',
    'in a romantic impressionist style',
    'with a vibrant and energetic design',
    'in a dreamy ethereal style',
    'with a detailed and intricate pattern',
    'in a bold minimalist style',
    'with a rich and deep color scheme',
    'in a bright and cheerful illustration style',
    'with a dark and moody atmosphere',
    'in a dynamic and vibrant style',
    'with a futuristic digital aesthetic',
    'in a soft and muted color palette',
    'with a detailed and realistic rendering',
    'in a playful cartoon style',
    'with a vibrant and eclectic mix of colors',
    'in a high-fidelity digital art style',
    'with a gritty urban texture',
    'in a sleek modern design',
    'with a soft and glowing light effect',
    'in a highly stylized illustration style',
    'with a dramatic chiaroscuro lighting',
    'in a richly textured art style',
    'with a bright and sunny color palette',
    'in a cool-toned digital painting style',
    'with a warm and inviting atmosphere',
    'in a highly abstract art style',
    'with a vibrant and dynamic brushwork',
    'in a clean and minimalist vector style',
    'with a vibrant and colorful composition',
    'in a detailed architectural illustration style',
    'with a soft and dreamy focus',
    'in a bold and expressive art style',
    'with a radiant and luminous color scheme',
    'in a highly detailed 3D render style',
    'with a vivid and saturated color palette',
    'in a classic oil painting technique',
    'with a smooth and polished finish',
    'in a vibrant and energetic digital art style',
    'with a soft and subtle color overlay',
    'in a dynamic and fluid illustration style',
    'with a rich and harmonious color harmony',
    'in a sophisticated and elegant art style',
    'with a bright and bold color splash',
    'in a smooth and flowing digital painting style',
    'with a detailed and lifelike texture',
    'in a playful and whimsical illustration style',
    'with a cool and calming color palette',
    'in a vibrant and intricate mosaic style',
    'with a warm and earthy tone',
    'in a dynamic and action-packed art style',
    'with a rich and layered color scheme',
    'in a clean and sharp vector illustration style',
    'with a vibrant and colorful digital overlay',
    'in a detailed and ornate art style',
    'with a soft and natural lighting effect',
    'in a highly realistic digital painting style',
    'with a bold and striking color contrast',
    'in a smooth and refined illustration style',
    'with a bright and lively color explosion',
    'in a highly stylized cartoon style',
    'with a vibrant and expressive brushstroke',
    'in a detailed and realistic oil painting style',
    'with a soft and diffused light effect',
    'in a dynamic and energetic art style',
    'with a vibrant and intense color palette',
    'in a sleek and modern digital illustration style',
    'with a detailed and precise linework',
    'in a vivid and bright watercolor style',
    'with a rich and deep tonal range',
    'in a playful and colorful comic style',
    'with a smooth and glossy digital finish',
    'in a highly abstract digital art style',
    'with a dynamic and fluid brushstroke effect',
    'in a richly detailed fantasy art style',
    'with a vibrant and dynamic color infusion',
    'in a clean and modern graphic style',
    'with a shimmering glow effect',
    'in a detailed and intricate design style',
    'with a vibrant and cheerful color palette',
    'in a smooth and glossy illustration style',
    'with a bright and sparkling light effect',
    'in a dynamic and bold graphic style',
    'with a rich oil texture',
    'in a detailed fantasy illustration',
    'with a vibrant graffiti look',
    'in a minimalistic monochrome style',
    'with a retro pixelated effect',
    'in a glossy digital art style',
    'with a vibrant gradient overlay',
    'in a high-definition realism style',
    'with a psychedelic color scheme',
    'in a soft pastel illustration style',
    'with a metallic sheen',
    'in a vibrant expressionist style',
    'with a digital glitch effect',
    'in a textured watercolor style',
    'with a monochrome color palette',
    'in a vibrant street art style',
    'with a digital painting finish',
    'in a dreamy soft-focus style',
    'with a dynamic vector graphic look',
    'in a traditional oil painting style',
    'with a layered collage effect',
    'in a stylized pop culture style',
    'with a retro arcade aesthetic',
    'in a bold and graphic style',
    'with a detailed architectural design',
    'in a high-saturation style',
    'with a luminous glow effect',
    'in a dynamic action illustration style',
    'with a sophisticated art nouveau influence',
    'in a crisp and clean vector style',
    'with a vibrant and dynamic color scheme',
    'in a classic renaissance painting style',
    'with a soft watercolor wash',
    'in a textured mixed media style',
    'with a sharp digital clarity',
    'in a romantic impressionist style',
    'with a vibrant and energetic design',
    'in a dreamy ethereal style',
    'with a detailed and intricate pattern',
    'in a bold minimalist style',
    'with a rich and deep color scheme',
    'in a bright and cheerful illustration style',
    'with a dark and moody atmosphere',
    'in a dynamic and vibrant style',
    'with a futuristic digital aesthetic',
    'in a soft and muted color palette',
    'with a detailed and realistic rendering',
    'in a playful cartoon style',
    'with a vibrant and eclectic mix of colors',
    'in a high-fidelity digital art style',
    'with a gritty urban texture',
    'in a sleek modern design',
    'with a soft and glowing light effect',
    'in a highly stylized illustration style',
    'with a dramatic chiaroscuro lighting',
    'in a richly textured art style',
    'with a bright and sunny color palette',
    'in a cool-toned digital painting style',
    'with a warm and inviting atmosphere',
    'in a highly abstract art style',
    'with a vibrant and dynamic brushwork',
    'in a clean and minimalist vector style',
    'with a vibrant and colorful composition',
    'in a detailed architectural illustration style',
    'with a soft and dreamy focus',
    'in a bold and expressive art style',
    'with a radiant and luminous color scheme',
    'in a highly detailed 3D render style',
    'with a vivid and saturated color palette',
    'in a classic oil painting technique',
    'with a smooth and polished finish',
    'in a vibrant and energetic digital art style',
    'with a soft and subtle color overlay',
    'in a dynamic and fluid illustration style',
    'with a rich and harmonious color harmony',
    'in a sophisticated and elegant art style',
    'with a bright and bold color splash',
    'in a smooth and flowing digital painting style',
    'with a detailed and lifelike texture',
    'in a playful and whimsical illustration style',
    'with a cool and calming color palette',
    'in a vibrant and intricate mosaic style',
    'with a warm and earthy tone',
    'in a dynamic and action-packed art style',
    'with a rich and layered color scheme',
    'in a clean and sharp vector illustration style',
    'with a vibrant and colorful digital overlay',
    'in a detailed and ornate art style',
    'with a soft and natural lighting effect',
    'in a highly realistic digital painting style',
    'with a bold and striking color contrast',
    'in a smooth and refined illustration style',
    'with a bright and lively color explosion',
    'in a highly stylized cartoon style',
    'with a vibrant and expressive brushstroke',
    'in a detailed and realistic oil painting style',
    'with a soft and diffused light effect',
    'in a dynamic and energetic art style',
    'with a vibrant and intense color palette',
    'in a sleek and modern digital illustration style',
    'with a detailed and precise linework',
    'in a vivid and bright watercolor style',
    'with a rich and deep tonal range',
    'in a playful and colorful comic style',
    'with a smooth and glossy digital finish',
    'in a highly abstract digital art style',
    'with a dynamic and fluid brushstroke effect',
    'in a richly detailed fantasy art style',
    'with a vibrant and dynamic color infusion',
    'in a clean and modern graphic style',
    'with a shimmering glow effect',
    'in a detailed and intricate design style',
    'with a vibrant and cheerful color palette',
    'in a smooth and glossy illustration style',
    'with a bright and sparkling light effect',
    'in a dynamic and bold graphic style',
    'with a rich oil texture',
    'in a detailed fantasy illustration',
    'with a vibrant graffiti look',
    'in a minimalistic monochrome style',
    'with a retro pixelated effect',
    'in a glossy digital art style',
    'with a vibrant gradient overlay',
    'in a high-definition realism style',
    'with a psychedelic color scheme',
    'in a soft pastel illustration style',
    'with a metallic sheen',
    'in a vibrant expressionist style',
    'with a digital glitch effect',
    'in a textured watercolor style',
    'with a monochrome color palette',
    'in a vibrant street art style',
    'with a digital painting finish',
    'in a dreamy soft-focus style',
    'with a dynamic vector graphic look',
    'in a traditional oil painting style',
    'with a layered collage effect',
    'in a stylized pop culture style',
    'with a retro arcade aesthetic',
    'in a bold and graphic style',
    'with a detailed architectural design',
    'in a high-saturation style',
    'with a luminous glow effect',
    'in a dynamic action illustration style',
    'with a sophisticated art nouveau influence',
    'in a crisp and clean vector style',
    'with a vibrant and dynamic color scheme',
    'in a classic renaissance painting style',
    'with a soft watercolor wash',
    'in a textured mixed media style',
    'with a sharp digital clarity',
    'in a romantic impressionist style',
    'with a vibrant and energetic design',
    'in a dreamy ethereal style',
    'with a detailed and intricate pattern',
    'in a bold minimalist style',
    'with a rich and deep color scheme',
    'in a bright and cheerful illustration style',
    'with a dark and moody atmosphere',
    'in a dynamic and vibrant style',
    'with a futuristic digital aesthetic',
    'in a soft and muted color palette',
    'with a detailed and realistic rendering',
    'in a playful cartoon style',
    'with a vibrant and eclectic mix of colors',
    'in a high-fidelity digital art style',
    'with a gritty urban texture',
    'in a sleek modern design',
    'with a soft and glowing light effect',
    'in a highly stylized illustration style',
    'with a dramatic chiaroscuro lighting',
    'in a richly textured art style',
    'with a bright and sunny color palette',
    'in a cool-toned digital painting style',
    'with a warm and inviting atmosphere',
    'in a highly abstract art style',
    'with a vibrant and dynamic brushwork',
    'in a clean and minimalist vector style',
    'with a vibrant and colorful composition',
    'in a detailed architectural illustration style',
    'with a soft and dreamy focus',
    'in a bold and expressive art style',
    'with a radiant and luminous color scheme',
    'in a highly detailed 3D render style',
    'with a vivid and saturated color palette',
    'in a classic oil painting technique',
    'with a smooth and polished finish',
    'in a vibrant and energetic digital art style',
    'with a soft and subtle color overlay',
    'in a dynamic and fluid illustration style',
    'with a rich and harmonious color harmony',
    'in a sophisticated and elegant art style',
    'with a bright and bold color splash',
    'in a smooth and flowing digital painting style',
    'with a detailed and lifelike texture',
    'in a playful and whimsical illustration style',
    'with a cool and calming color palette',
    'in a vibrant and intricate mosaic style',
    'with a warm and earthy tone',
    'in a dynamic and action-packed art style',
    'with a rich and layered color scheme',
    'in a clean and sharp vector illustration style',
    'with a vibrant and colorful digital overlay',
    'in a detailed and ornate art style',
    'with a soft and natural lighting effect',
    'in a highly realistic digital painting style',
    'with a bold and striking color contrast',
    'in a smooth and refined illustration style',
    'with a bright and lively color explosion',
    'in a highly stylized cartoon style',
    'with a vibrant and expressive brushstroke',
    'in a detailed and realistic oil painting style',
    'with a soft and diffused light effect',
    'in a dynamic and energetic art style',
    'with a vibrant and intense color palette',
    'in a sleek and modern digital illustration style',
    'with a detailed and precise linework',
    'in a vivid and bright watercolor style',
    'with a rich and deep tonal range',
    'in a playful and colorful comic style',
    'with a smooth and glossy digital finish',
    'in a highly abstract digital art style',
    'with a dynamic and fluid brushstroke effect',
    'in a richly detailed fantasy art style',
    'with a vibrant and dynamic color infusion',
    'in a clean and modern graphic style',
    'with a shimmering glow effect',
    'in a detailed and intricate design style',
    'with a vibrant and cheerful color palette',
    'in a smooth and glossy illustration style',
    'with a bright and sparkling light effect',
    'in a dynamic and bold graphic style',
    'with a rich oil texture',
    'in a detailed fantasy illustration',
    'with a vibrant graffiti look',
    'in a minimalistic monochrome style',
    'with a retro pixelated effect',
    'in a glossy digital art style',
    'with a vibrant gradient overlay',
    'with a soft and dreamy color gradient'
];




    const extraLists = [extraList1, extraList2, extraList3, extraList4, extraList5];

    // Function to add extra items to the prompt
    function addStuff(prompt) {
        const numExtras = Math.floor(Math.random() * 17) + 1; // Random number between 1 and 5
        let addedExtras = [];

        for (let i = 0; i < numExtras; i++) {
            // Randomly select one of the lists
            const listIndex = Math.floor(Math.random() * extraLists.length);
            const selectedList = extraLists[listIndex];
            // Randomly select an item from the list
            const itemIndex = Math.floor(Math.random() * selectedList.length);
            const selectedItem = selectedList[itemIndex];
            // Add the selected item to the array
            addedExtras.push(selectedItem);
        }

        // Append the extra items to the prompt
        return prompt + ', ' + addedExtras.join(', ');
    }

    // Function to set the value natively (works with React and similar frameworks)
    function setNativeValue(element, value) {
        const valueSetter = Object.getOwnPropertyDescriptor(Object.getPrototypeOf(element), 'value').set;
        valueSetter.call(element, value);
        element.dispatchEvent(new Event('input', { bubbles: true }));
    }

    // Function to click the button when it's enabled
    function waitForButtonAndClick(callback) {
        var button = document.querySelector('button[aria-label="Grok something"]');

        if (button) {
            console.log('Button found.');
            if (!button.disabled) {
                button.click();
                console.log('Button clicked!');
                if (callback) callback();
            } else {
                console.log('Button is disabled, waiting...');
                setTimeout(function() {
                    waitForButtonAndClick(callback);
                }, 500);
            }
        } else {
            console.error('Button not found!');
            setTimeout(function() {
                waitForButtonAndClick(callback);
            }, 500);
        }
    }

    // Function to process the image at a specific index from the end
    function processImage(imageIndex = 5) {
        console.log(`Processing the image at index images.length - ${imageIndex}...`);

        const images = document.querySelectorAll('img');

        if (images.length < imageIndex) {
            console.error('Not enough images on the page.');
            setTimeout(() => {
                console.log('Restarting the script due to insufficient images...');
                automateInteraction();
            }, 5000); 
            return;
        }

        const targetImage = images[images.length - imageIndex];

        if (lastProcessedImageSrc === targetImage.src) {
            console.log('Image is the same as the last processed one. Restarting the script...');
            setTimeout(() => {
                automateInteraction();
            }, 5000); 
            return;
        }

        lastProcessedImageSrc = targetImage.src;

        if (targetImage.naturalWidth <= 100 || targetImage.naturalHeight <= 100) {
            console.log('Image is too small (less than 100x100 pixels). Restarting the script...');
            handleImageSizeError();
            return;
        }

        if (!targetImage.complete || targetImage.naturalWidth === 0) {
            console.log('Image not fully loaded. Waiting for load event.');
            targetImage.onload = function() {
                saveImage(targetImage, imageIndex);
            };
            targetImage.onerror = function() {
                console.error('Error loading image.');
                handleImageSizeError();
            };
        } else {
            saveImage(targetImage, imageIndex);
        }
    }

    // Function to save the image
    function saveImage(imgElement, imageIndex) {
        console.log('Saving image...');

        try {
            imgElement.scrollIntoView({ behavior: 'smooth', block: 'center' });

            setTimeout(() => {
                const canvas = document.createElement('canvas');
                canvas.width = imgElement.naturalWidth;
                canvas.height = imgElement.naturalHeight;

                const ctx = canvas.getContext('2d');
                ctx.drawImage(imgElement, 0, 0);

                canvas.toBlob((blob) => {
                    if (!blob) {
                        console.error('Failed to convert canvas to blob.');
                        handleImageSizeError();
                        return;
                    }

                    const url = URL.createObjectURL(blob);

                    const a = document.createElement('a');
                    a.href = url;
                    a.download = `image_${Date.now()}.png`;
                    document.body.appendChild(a);

                    a.click();
                    console.log('Image download triggered.');

                    setTimeout(() => {
                        document.body.removeChild(a);
                        URL.revokeObjectURL(url);
                    }, 100);

                    // Reset error count upon success
                    localStorage.setItem('errorCount', '0');

                    setTimeout(() => {
                        console.log('Restarting the script...');
                        automateInteraction();
                    }, 5000); 
                }, 'image/png');
            }, 500); 
        } catch (error) {
            console.error('Failed to save image:', error);

            if (error.message.includes('SecurityError')) {
                console.log('SecurityError encountered. Retrying with next image...');
                handleSecurityError(imageIndex + 1);
            } else {
                handleImageSizeError();
            }
        }
    }

    // Function to handle SecurityError with image retries
    function handleSecurityError(nextImageIndex) {
        // Maximum of 5 additional attempts
        const maxRetries = 5;

        // Calculate how many retries have been attempted
        const retryCount = nextImageIndex - 5;

        if (retryCount <= maxRetries) {
            console.log(`Retrying with image at index images.length - ${nextImageIndex} (Retry ${retryCount} of ${maxRetries})...`);
            setTimeout(() => {
                processImage(nextImageIndex);
            }, 5000); // Wait 5 seconds before retrying
        } else {
            console.log('Exceeded maximum retries for SecurityError. Moving on to generate a new image...');
            // Reset error count and proceed
            localStorage.setItem('errorCount', '0');
            setTimeout(() => {
                automateInteraction();
            }, 5000); 
        }
    }

    // Function to handle errors related to small images or loading errors
    function handleImageSizeError() {
        errorCount++;
        console.log(`Image size issue or SecurityError encountered. Error count: ${errorCount}`);
        localStorage.setItem('errorCount', errorCount);

        if (errorCount >= 2) {
            console.log('Error occurred twice. Waiting 20 minutes before restarting...');
            setTimeout(() => {
                console.log('Restarting the script after 20 minutes...');
                localStorage.setItem('errorCount', '0'); // Reset error count
                automateInteraction();
            }, 20 * 60 * 1000); 
        } else {
            console.log('Restarting the script immediately due to image size or SecurityError...');
            setTimeout(() => {
                automateInteraction();
            }, 5000); 
        }
    }

    // Function to start automation
    function startAutomation() {
        var textarea = document.querySelector('textarea[placeholder="Ask anything"]');

        if (!textarea) {
            console.error('Textarea not found!');
            setTimeout(() => {
                startAutomation();
            }, 5000); 
        } else {
            console.log('Textarea found.');

            const randomNum = Math.random();
            let finalPrompt = basePrompt;
            if (randomNum < 0.6) {
                console.log('Using base prompt without additions.');
            } else {
                console.log('Adding extra items to the prompt.');
                finalPrompt = addStuff(basePrompt);
            }

            setNativeValue(textarea, finalPrompt);
            console.log(`Set textarea value to: "${finalPrompt}".`);

            waitForButtonAndClick(function() {
                console.log('Button clicked! Waiting 30 seconds before processing the image...');
                setTimeout(function() {
                    console.log('Processing the image...');
                    processImage();
                }, 30000); 
            });
        }
    }

    // Start the automation process
    startAutomation();

})();
